spring:
    datasource:
        url: jdbc:mysql://localhost:3306/onework
        username: root
        password: 12341234
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
spring.main.allow-bean-definition-overriding: true

logging:
    level:
        org:
            hibernate:
                SQL: debug
                orm:
                    jdbc:
                        bind: trace
                springframework:
                    security: debug

jwt:
    secret-key: fjfkjkfeJEKFWLFEJwlfkwelfjwkeJRkljskeaejfsakjflfklfjelKASKE
    issuer: one
    expiration-hours: 3